### ISSUE TITLE
Unable to use MotionView in SkipWeather app

### ISSUE THREAD

**Issue by ekahannah** [skiptools/skip-motion#1]
Hi, I recently tried using the MotionView in Skipweather app. I also retrieved the skip-motion library
Attached is the code snippet:

![Screenshot 2023-11-15 at 3 22 09 PM](https://github.com/skiptools/skip-motion/assets/1568192/abefb02b-7b3d-45b3-b225-815965f23096)

However, when I build the app, I get this error: 
`
ld: Undefined symbols:
  SkipMotion.MotionView.init(lottie: Foundation.Data) -> SkipMotion.MotionView, referenced from:
      closure #1 () -> SwiftUI.TupleView<(SkipMotion.MotionView, SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)> in closure #1 () -> SwiftUI.TupleView<(SwiftUI.HStack<SwiftUI.TupleView<(SkipMotion.MotionView, SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)>>, SwiftUI.HStack<SwiftUI.TupleView<(SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)>>, SwiftUI.NavigationLink<SwiftUI.Text, Swift.Never>, SwiftUI.NavigationLink<SwiftUI.Text, Swift.Never>)> in SkipWeather.SettingsView.body.getter : some in SkipWeather.o
  protocol conformance descriptor for SkipMotion.MotionView : SwiftUI.View in SkipMotion, referenced from:
      lazy protocol witness table accessor for type SkipMotion.MotionView and conformance SkipMotion.MotionView : SwiftUI.View in SkipMotion in SkipWeather.o
  nominal type descriptor for SkipMotion.MotionView, referenced from:
      _symbolic _____y__________y_____yACy________________AF_____y_____yAFG_Qo_tGG_ADyACyAF_AgfJtGG_____yAfBGAPtGG 7SwiftUI4ListV s5NeverO AA9TupleViewV AA6HStackV 10SkipMotion0iF0V AA4TextV AA6SpacerV AA0F0PAAE12labelsHiddenQryFQO AA6ToggleV AA14NavigationLinkV in SkipWeather.o
      _symbolic _____y_____y__________y_____yACy________________AF_____y_____yAFG_Qo_tGG_ADyACyAF_AgfJtGG_____yAfBGAPtGG___________y______SSQo_Qo_ 7SwiftUI4ViewPAAE21navigationDestination3for11destinationQrqd__m_qd_0_qd__ctSHRd__AaBRd_0_r0_lFQO AA4ListV s5NeverO AA05TupleC0V AA6HStackV 10SkipMotion0mC0V AA4TextV AA6SpacerV AcAE12labelsHiddenQryFQO AA6ToggleV AA14NavigationLinkV 10Foundation3URLV AcAE0D5TitleyQrqd__SyRd__lFQO 0L7Weather03WebC0V in SkipWeather.o
      _symbolic _____y_____y_____y__________y_____yACy________________AF_____y_____yAFG_Qo_tGG_ADyACyAF_AgfJtGG_____yAfBGAPtGG___________y______SSQo_Qo__So13NSProcessInfoC_____yAAyAB_____ySay_____GSSADyACyAF_AgFtGGGG_Qo_Qo_ 7SwiftUI4ViewPAAE21navigationDestination3for11destinationQrqd__m_qd_0_qd__ctSHRd__AaBRd_0_r0_lFQO AcAEAdeFQrqd__m_qd_0_qd__ctSHRd__AaBRd_0_r0_lFQO AA4ListV s5NeverO AA05TupleC0V AA6HStackV 10SkipMotion0mC0V AA4TextV AA6SpacerV AcAE12labelsHiddenQryFQO AA6ToggleV AA14NavigationLinkV 10Foundation3URLV AcAE0D5TitleyQrqd__SyRd__lFQO 0L7Weather03WebC0V AcAEA2_yQrAA18LocalizedStringKeyVFQO AA7ForEachV A3_08SettingsC0V3Env33_EDEC5654EC7AC3BA216D9EFC2C5FF5FELLV in SkipWeather.o
      _symbolic _____y_____yAAy________________AD_____y_____yADG_Qo_tGG_AByAAyAD_AedHtGG_____yAD_____GAOtG 7SwiftUI9TupleViewV AA6HStackV 10SkipMotion0gD0V AA4TextV AA6SpacerV AA0D0PAAE12labelsHiddenQryFQO AA6ToggleV AA14NavigationLinkV s5NeverO in SkipWeather.o
      _symbolic _____y_____y________________AD_____y_____yADG_Qo_tGG 7SwiftUI6HStackV AA9TupleViewV 10SkipMotion0gE0V AA4TextV AA6SpacerV AA0E0PAAE12labelsHiddenQryFQO AA6ToggleV in SkipWeather.o
      _symbolic _____y________________AC_____y_____yACG_Qo_tG 7SwiftUI9TupleViewV 10SkipMotion0fD0V AA4TextV AA6SpacerV AA0D0PAAE12labelsHiddenQryFQO AA6ToggleV in SkipWeather.o
      _symbolic _____y___________y________________AE_____y_____yAEG_Qo_tGG 7SwiftUI13_VariadicViewO4TreeV AA13_HStackLayoutV AA05TupleD0V 10SkipMotion0jD0V AA4TextV AA6SpacerV AA0D0PAAE12labelsHiddenQryFQO AA6ToggleV in SkipWeather.o
      ...
  type metadata for SkipMotion.MotionView, referenced from:
      closure #1 () -> SwiftUI.TupleView<(SkipMotion.MotionView, SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)> in closure #1 () -> SwiftUI.TupleView<(SwiftUI.HStack<SwiftUI.TupleView<(SkipMotion.MotionView, SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)>>, SwiftUI.HStack<SwiftUI.TupleView<(SwiftUI.Text, SwiftUI.Spacer, SwiftUI.Text, <<opaque return type of (extension in SwiftUI):SwiftUI.View.labelsHidden() -> some>>.0)>>, SwiftUI.NavigationLink<SwiftUI.Text, Swift.Never>, SwiftUI.NavigationLink<SwiftUI.Text, Swift.Never>)> in SkipWeather.SettingsView.body.getter : some in SkipWeather.o
      lazy protocol witness table accessor for type SkipMotion.MotionView and conformance SkipMotion.MotionView : SwiftUI.View in SkipMotion in SkipWeather.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by aabewhite** [comment]
Sorry for the trouble. Can you please post your Package.swift file?

**Comment by ekahannah** [comment]
Hi @aabewhite , 

Thanks for the tip. Yeah apparently, Skip motion was not added as dependency in the package.swift file even though I already imported it via the swift package manager. 

After manually adding the skip-motion dependecy, the app build properly. 

Attached is the working Package.swift
```
// swift-tools-version: 5.9
// This is a Skip (https://skip.tools) package,
// containing a Swift Package Manager project
// that will use the Skip build plugin to transpile the
// Swift Package, Sources, and Tests into an
// Android Gradle Project with Kotlin sources and JUnit tests.
import PackageDescription
import Foundation

// Set SKIP_ZERO=1 to build without Skip libraries
let zero = ProcessInfo.processInfo.environment["SKIP_ZERO"] != nil
let skipstone = !zero ? [Target.PluginUsage.plugin(name: "skipstone", package: "skip")] : []

let package = Package(
    name: "skipapp-weather",
    defaultLocalization: "en",
    platforms: [.iOS(.v16), .macOS(.v13), .tvOS(.v16), .watchOS(.v9), .macCatalyst(.v16)],
    products: [
        .library(name: "SkipWeatherApp", type: .dynamic, targets: ["SkipWeather"]),
        .library(name: "SkipWeatherModel", type: .dynamic, targets: ["SkipWeatherModel"]),
    ],
    dependencies: [
        .package(url: "https://source.skip.tools/skip.git", from: "0.7.25"),
        .package(url: "https://source.skip.tools/skip-ui.git", from: "0.0.0"),
        .package(url: "https://source.skip.tools/skip-foundation.git", from: "0.0.0"),
        .package(url: "https://source.skip.tools/skip-model.git", from: "0.0.0"),
        .package(url: "https://source.skip.tools/skip-motion.git", from: "0.0.0")
    ],
    targets: [
        .target(name: "SkipWeather", dependencies: ["SkipWeatherModel"] + (zero ? [] : [.product(name: "SkipUI", package: "skip-ui")]), resources: [.process("Resources")], plugins: skipstone),
        .testTarget(name: "SkipWeatherTests", dependencies: ["SkipWeather"] + (zero ? [] : [.product(name: "SkipTest", package: "skip")]), resources: [.process("Resources")], plugins: skipstone),
        .target(name: "SkipWeatherModel", dependencies: (zero ? [] : [.product(name: "SkipFoundation", package: "skip-foundation"), .product(name: "SkipModel", package: "skip-model"),
            .product(name: "SkipMotion", package: "skip-motion")]), resources: [.process("Resources")], plugins: skipstone),
        .testTarget(name: "SkipWeatherModelTests", dependencies: ["SkipWeatherModel"] + (zero ? [] : [.product(name: "SkipTest", package: "skip")]), resources: [.process("Resources")], plugins: skipstone),
    ]
)
```

Closing this issue since it was already resolved. Thanks again!
